### ISSUE TITLE
Dynamic Print button from index doesn't work.

### ISSUE THREAD

**Issue by oggiesutrisna** [oggiesutrisna/DokterOne#3]
can someone solve the problem? any help will be appreciated. Thank you.

**Comment by mrizkimaulidan** [comment]
let me try to fix, i will open the PR later if im solved the problem

**Comment by mrizkimaulidan** [comment]
> can someone solve the problem? any help will be appreciated. Thank you.

i have made a PR in #4 please review what i have made

**Comment by oggiesutrisna** [comment]
it says "cannot find the archive file"

**Comment by oggiesutrisna** [comment]
all of your commits are already merged and reviewed. Thanks for your hardwork, i'll be come in a hour
